#spring.application.name=eureka-server

#spring.application.name=UnicornServer
# Eureka Server?? ????? ???? port?(?? ? ?? ?? ??)
server:
  port: 8766

# Eureka  Server? ?? ??? Server?? ??? Server? ???? ?? ???
# register-with-eureka: false?? ??

# ?? ???? ????? ???? ???? ?? ??? fetch-registry: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8766/eureka